### ISSUE TITLE
Corrupted image files

### ISSUE THREAD

**Issue by zachwolf** [wj42ftns/replace-in-files#22]
Hello! Thanks for your work on this package, it's been very helpful for my work.

I'm running into an issue where running the package on a directory with images cause those files to become corrupted. I've created a [simplified example](https://github.com/zachwolf/replace-in-files-reduces-test-case) to make it easier to test.

To reproduce:

- `git clone git@github.com:zachwolf/replace-in-files-reduces-test-case.git`
- `cd replace-in-files-reduces-test-case`
- `npm i`
- `npm start`
- `git status`

Notice that the favicon is now reporting a binary diff, and it can not be opened by browsers.

<img width="621" alt="Screen Shot 2019-04-30 at 3 56 44 PM" src="https://user-images.githubusercontent.com/606237/56992996-e84e7880-6b60-11e9-99f7-f24e03ce18af.png">

I know that there are options and glob matches to work with this already provided. It would be very helpful if the default behavior only ran replace on string-like content. I'm not sure what the use case would be for replacing in image files intentionally.

Thanks again!

**Comment by wj42ftns** [comment]
This logic updated in v2+
Now there is new option: `shouldSkipBinaryFiles` this flag is `true` by default.
