### ISSUE TITLE
Empty "to" value

### ISSUE THREAD

**Issue by mrveress** [wj42ftns/replace-in-files#29]
Hello! Simple issue: most important feature for replacing (at least for me) it's changing value from some string to empty string.
If I trying to do something like:
`
let options = {
		files: ['../src/*', '../src/**/*'],
		from: /test/gm,
		to: ""
	}
`
I always have only occurrences in result, but files not changing.
Node version: v11.5.0
Package version: Latest at the moment.

Thanks in advance!

**Comment by avisser** [comment]
@mrveress Every get a solution? Doesn't seem to work with a function either `() => ''`

**Comment by avisser** [comment]
@wj42ftns The issue is here https://github.com/wj42ftns/replace-in-files/blob/master/lib/Configurator.js#L27

`> !!'' //false`

This needs to be a test against `null` and `undefined`

**Comment by avisser** [comment]
@mrveress I was wrong. You can use a function that returns `''` as a work-around

**Comment by mrveress** [comment]
@avisser got it, thanks! Anyway, as I understand, it should be natively supported without workarounds, but yeah, workarounds it's our everything)
