### ISSUE TITLE
Not replace in binary file

### ISSUE THREAD

**Issue by scorpioRED** [wj42ftns/replace-in-files#32]
I have file called **AndroidManifest.xml** which is - **application/octet-stream; charset=binary** (file -I AndroidManifest.xml)
Here is a screenshot from my ide when I try to open it

[https://i.ibb.co/48Vn1H2/Screenshot-2020-09-02-at-16-47-17.png](url)

In options, I have set
`shouldSkipBinaryFiles: false`
But it's doesn't help :(

**Comment by wj42ftns** [comment]
I switched is binary checker lib - I hope it will help: 
https://github.com/wj42ftns/replace-in-files/commit/dce6f268d697379a98659bca4fa9fa3b92943c6f
If not give me please an example with a broken case.
You can test changes in v3.0.0
