### ISSUE TITLE
Replace patterns with $ don't work

### ISSUE THREAD

**Issue by DanielSWolf** [wj42ftns/replace-in-files#35]
`string.replace` allows patterns like `'$1'` in the `to` string to refer to capture groups. These patterns don't work in this library. Instead, the literal string `'$1'` is inserted.

**Comment by wj42ftns** [comment]
After this commit it should work:
https://github.com/wj42ftns/replace-in-files/pull/37/commits/a9cd4b1a98387eb742704e5ef3e2bcaad135b988
You can use v3.0.0 with this fix.
